# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79d0cef0873f9f755aa3297c31d9a059d6208dce4b392f9bc383491da2bf4332616d31cdafafaff65f33e676449b2e4c69cc3668cfbb1437bb99f69f51f1e94b

test:
  secret_key_base: 61255bab093932200b85bc680dbccbae13a49099df38052cf300c939d67f14ad004453d1bc50b3141c2131652c745e49e13c564e709ab933f03f442050ac2693

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
